title: Azure Services Category
description: Azure services personal documentation
url: azure.msft.vip
remote_theme: rundocs/jekyll-rtd-theme

# folders sort
readme_index:
  with_frontmatter: true

#meta:
#  key1: value1
#  key2: value2

# 默认为所有文章启用 toc
defaults:
  - scope:
      path: ""
    values:
      toc: true

google:
  gtag:
  adsense:

mathjax: # this will prased to json, default: {}

mermaid:
  custom:     # mermaid link
  initialize: # this will prased to json, default: {}

scss: # _includes/extra/styles.scss
script: #_includes/extra/script.js

translate:
  # shortcodes
  danger: _includes/shortcodes/danger.liquid
  note: _includes/shortcodes/note.liquid
  tip: _includes/shortcodes/tip.liquid
  warning: _includes/shortcodes/warning.liquid
  # 404
  not_found: assets/404.liquid
  # copyright
  revision: Jas0n0ss
  # search
  searching:
  search:
  search_docs:
  search_results:
  search_results_found: # the "#" in this translate will replaced with results size!
  search_results_not_found:

plugins:
#	- jekyll-toc
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
